# azure-pipeline.yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.17.x'
  displayName: 'Install Go'

- script: |
    go build -o aix main.go
    ./aix
  displayName: 'Build and run application'
